### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Nevotic** [ApolloZhu/Dynamic-Dark-Mode#12]
I'm having issues with compiling it and installing it. Any steps I can follow to see if I'm not doing something wrong? Or do you have a direct download for the compiled version?

**Comment by ApolloZhu** [comment]
I don’t really want to offer direct downloads (yet) since I haven’t implemented auto update. But if this doesn’t pass the MAS review (which is very likely), I’ll upload some prereleases after school today.

The reason it doesn’t compile is most likely because I set the development team to mine and registered the bundle identifier. You can either:

1. Replace them with your account
2. Or if you don’t have one,
  1. Change development team to None
  2. Change the bundle identifier if Xcode says it’s been occupied
  3. Click the word “Dynamic” on the right the stop button in the top left corner
  4. Select Edit Scheme
  5. Change the configuration to Release-MASless.

That should solve the problem. If not, upload some screenshots of the error. Or we can talk about this over email (public-apollonian@outlook.com) if you don’t want to publicly share your screenshot online.

**Comment by Nevotic** [comment]
I'm not too keen on Xcode so I'll probably just keep an eye out for the final release to the App Store if that will be accepted hopefully. 👍

**Comment by ApolloZhu** [comment]
I'll add compilation instructions later, but for now, here's the compiled binary

https://github.com/ApolloZhu/Dynamic-Dark-Mode/releases
