### ISSUE TITLE
Failed to toggle dark mode  NSAppleScriptErrorNumber 43

### ISSUE THREAD

**Issue by etrahretep** [ApolloZhu/Dynamic-Dark-Mode#68]
Failed to toggle dark mode
NSAppleScriptErrorNumber 43
Version 1.3
Running macOS 10.14.6 bèta (18G29g)

**Comment by ApolloZhu** [comment]
Version 1.3.0 works fine on macOS 10.14.4. I'll get back to you as soon as I update to beta os and test the app on it.

Since error 43 usually means "file not found", my hypothesis is that AppleScript couldn't find the frontmost, focused application. If you don't mind to share, what app were you using when dark mode toggle is triggered?

**Comment by etrahretep** [comment]
Downloaded the zip instead of pkg. Working now!
No idea what caused it. Only finder was open when toggling.

**Comment by ApolloZhu** [comment]
Interestingly, both zip and pkg works for me on macOS 10.14.6 beta. Not sure what happened but I'm glad it worked out in the end ;)

**Comment by ApolloZhu** [comment]
@Vince14Genius you mentioned -43 in #22, are you also experiencing this issue these days with 1.3.0?
