### ISSUE TITLE
Allow controlling system events won't start DDM

### ISSUE THREAD

**Issue by etrahretep** [ApolloZhu/Dynamic-Dark-Mode#75]
![Schermafbeelding 2019-09-14 om 17 54 16](https://user-images.githubusercontent.com/42773309/64910655-ebfe2880-d718-11e9-9cca-b50c054b0a50.png)

Can't get any further with this!
Catalina 10.15 bèta (19A558d)

**Comment by ApolloZhu** [comment]
Hmmm... even if you click on “Check Permission” / reopening the app? That would be very strange

**Comment by etrahretep** [comment]
No, every time I open the app it asks to check permissions. Which are checked. Starting the app with controlled hold opens the preferences but won't hold after restart.
Tried different versions of DDM (1.2 to 1.5 won't precede, 1.1.5 does)

**Comment by ApolloZhu** [comment]
Interestingly, no code changes were made towards checking System Events permission between 1.1.5 and 1.2.0, so I don't see why 1.1.5 works but not 1.2.0 and above. I even changed my system language to Dutch, still all versions goes through the process.

I guess I'll add an option to bypass the check (although probably something won't work), but here are some questions I wish you could answer (which might help me understanding why this is happening):

- [ ] What do you mean by "with controlled hold"? 
- [ ] By "won't hold after restart" you mean DDM don't have the System Events permission check after restarting macOS?

Also, this is what I found [online](https://bitsplitting.org/2018/07/11/reauthorizing-automation-in-mojave/):

> "quit and reopened Xcode (the TCC privileges seem to be cached"

That is, the permission system since Mojave might cache the current state before changes are applied. DDM used to require reopening DDM after changing permission, although later that became unnecessary with a Mojave update.

- [ ] If you have to reopen DDM after giving it permission and everything works, there is a chance that macOS permission system has a caching bug.

**Comment by etrahretep** [comment]
After restart the setup screen appears and when clicking that the check permissions message pops up again. Double clicking the app again (with the permissions screen open) opens preferences behind that screen. I can change settings but after restart the setup screen reappears....

**Comment by ApolloZhu** [comment]
That does sound like another bug. I'll add an option to skip the setup process and see how that works out.

**Comment by ApolloZhu** [comment]
1.5.1 allows you to skip setup and execute AppleScript even when DDM think you didn't give it the permission to do so. Give it a try and see if can run the AppleScript without any issue. If AppleScript fails like it has been, I might consider using another approach.

**Comment by etrahretep** [comment]
Apollo,

Still problems when togging darkmode...

![Schermafbeelding 2019-09-19 om 08 37 33](https://user-images.githubusercontent.com/42773309/65219908-e3f80d00-dab9-11e9-8be6-e49804c28bc8.png)
![Schermafbeelding 2019-09-19 om 08 37 54](https://user-images.githubusercontent.com/42773309/65219909-e3f80d00-dab9-11e9-84f4-dca53ac45df4.png)

**Comment by ApolloZhu** [comment]
Than that’s a bug on Apple’s side and you may want to report it to them somehow.

Meanwhile, I’ll switch to an alternative implementation to achieve the same goal in next release .

**Comment by etrahretep** [comment]
Using Catalina 10.15 bèta (19A558d). I'll wait out the GM and see what happens.

**Comment by ApolloZhu** [comment]
Better report it early so they know there is a bug to fix. And the more people report, earlier they get their hands on solving it.

**Comment by etrahretep** [comment]
Right, done!

**Comment by ApolloZhu** [comment]
Please update to 1.5.2
